### ISSUE TITLE
How to launch window with single pane and no command?

### ISSUE THREAD

**Issue by rawbeans** [TomAnthony/itermocil#112]
How do I launch a window without running a command?

Currently I can do one of the following but they seem hacky or redundant:

```
windows:
  - name: test
    root: ~/test/dir
    panes:
      - echo
```

```
windows:
  - name: test2
    root: ~/test/dir
    panes:
      - cd ~/test/dir
```

```
windows:
  - name: test3
    root: ~/test/dir
    command: cd ~/test/dir
```

**Comment by chrisfosterelli** [comment]
@rawbeans You can specify no command with `{}`:

```
windows:
  - name: test3
    root: ~/test/dir
    command: {}
```
