### ISSUE TITLE
Add badge support

### ISSUE THREAD

**Issue by sp4ce** [TomAnthony/itermocil#115]
Hello,

it would be nice if itermocil could support badge. For example

```
windows:
  - name: badge
    root: ~
    badge: badge
    commands:
      - echo badge
```

![Screen Shot 2021-03-08 at 13 49 52](https://user-images.githubusercontent.com/497642/110386510-39f5a300-8015-11eb-96c8-107bfde7ffa2.png)
