### ISSUE TITLE
Commands only run for the last pane

### ISSUE THREAD

**Issue by kirankunigiri** [TomAnthony/itermocil#129]
I used one of the example yaml setups and tried a few commands. Only the last pane seems to actually run the command. If I use more than 3 panes, sometimes a few more will run but it seems random. I was originally using it to ssh into 3 different servers for each pane, but as a more simple example I am just running `echo "Hello"` for each pane. Only the last pane successfully executes the `echo` while nothing happens in the first two. The first two also don't `cd` into the correct directory.

I am using iTerm v3.3.7

My yaml file:
```
windows:
  - name: main-vertical
    root: /Users/kiran.kunigiri/Documents
    layout: double-main-horizontal
    panes:
      - echo "Hello1"
      - echo "Hello2"
      - echo "Hello3"
```

Result:
![iTerm](https://i.imgur.com/YKpiJNn.png)

**Comment by godbout** [comment]
there's been issues with iTerm 3.3.x: https://github.com/TomAnthony/itermocil/issues/97

try updating to 3.4.x. haven't had any issue with those versions yet.

**Comment by godbout** [comment]
best it to always use the latest version of iTerm: https://iterm2.com/version3.html

**Comment by godbout** [comment]
and for reference, your yaml is good:

https://user-images.githubusercontent.com/121373/188274937-38c8e608-f03f-4c8c-8629-74d7fea6484c.mp4

**Comment by kirankunigiri** [comment]
I just updated to Build 3.4.16, but I'm still having the same issue.

**Comment by godbout** [comment]
which version of iTermocil you're running? if it's the latest could it be possible that some zsh config or some other plugins (if you use oh-my-zsh etc.) are doing this? coz works fine on my side.

**Comment by Leeiio** [comment]
same here.
iTermocil version is 1.0.3, iTerm2 version is 3.4.16.
My yaml file:
```
windows:
  - name: test
    root: ~
    layout: tiled
    panes:
      - commands:
          - ls
      - commands:
          - ls
      - commands:
          - ls
        focus: true
      - commands:
          - ls
```
![2022-09-06 13 03 19](https://user-images.githubusercontent.com/218127/188550927-03efaae9-4e4a-4d0e-a87b-a324bdcbb3e0.png)

Everything is ok in last week.

**Comment by godbout** [comment]
hmm. same. working fine here.

anything you did within the last week? updated macOS? python?

what version of macOS are you guys running? and python.

**Comment by kirankunigiri** [comment]
I completely deleted and reset my zsh config but the same issue occurs.
macOS Monterey v12.5
python3 v3.10.6
iTerm v3.4.16

**Comment by godbout** [comment]
@kirankunigiri what's your version of iTermocil? it's hard to help if we're not having the minimum info. even more while it works fine here.

i'm on Ventura beta. will try on Monterey later on.

**Comment by kirankunigiri** [comment]
I just installed it, so I have the latest itermocil 1.0.3

**Comment by godbout** [comment]
@kirankunigiri 

can you try this yaml, just to make sure it's not related to some yaml structure? thanks.

```
windows:

  - name: code
    root: ~/Development/Wooshy/sources
    layout: even-vertical
    panes:
      - commands:
        - cd Core
        - clear
        - git status
        focus: true
      - commands:
        - cd AXEngine2
        - clear
        - git status
      - commands:
        - cd ../../AppCatalog
        - clear
        - git status
  - name: docs and site
    root: ~/Development/Wooshy
    layout: even-vertical
    panes:
      - commands:
        - cd docs
        - clear
        - git status
      - commands:
        - cd sites/wooshy
        - clear
        - git status
```

it's not gonna find the folders but it should still run the commands.
