### ISSUE TITLE
Feature Request: Specify profiles for new windows / panes

### ISSUE THREAD

**Issue by j1mmie** [TomAnthony/itermocil#131]
Since iTerm supports profiles for windows and tabs, it could be helpful in an itermocil config to be able to specify which profile to use for a window or pane.

For example:

```
windows:
  - name: profiles_test
    root: ~
    layout: main-horizontal
    panes:
      - name: Top
        profile: "Top-Profile"
        commands:
          - echo "I'm the top"
      - name: Bottom
        profile: "Bottom-Profile"
        commands:
          - echo "I'm the bottom"
```

This way, the user could specify different colors / themes using iTerm2 profiles. For example:
![image](https://user-images.githubusercontent.com/4650220/196544842-8d5cc7a6-f959-4a18-8192-861babc819db.png)
