### ISSUE TITLE
Running itermocil inside itermocil

### ISSUE THREAD

**Issue by sourabh-bcg** [TomAnthony/itermocil#137]
I have a few configs like these

proj1.yml
```yml
windows:
  - name: "..."
    root: ~/proj1
    layout: even-vertical
    panes:
      - name: "pane1"
        commands:
          - make
        focus: true
      - name: "pane2"
        commands:
          - npm start
```

where proj1 changes to support a few projects (with some alteration in commands of panes as well)
I made an alias `export i="itermocil --here"` to run it as `$ i proj1`

Now `i proj1` and `i proj2` work fine but I wanted a way to run all of them together so i wrote another config

**all.yml**
```yml
windows:
  - name: "proj1"
    root: ~/proj1
    panes:
      - name: 'proj1'
        commands:
          - i proj1
  - name: "proj2"
    root: ~/proj2
    panes:
      - name: 'proj2'
        commands:
          - i proj2
```

Now this commands runs all the commands of panes but instead launches all the panes in last terminal tab instead of running proj1 in first tab and proj2 in second tab
