### ISSUE TITLE
Just tabs with a single pane?

### ISSUE THREAD

**Issue by RickGroenewegen** [TomAnthony/itermocil#140]
Is it possible to create several tabs with all just a single pane?

**Comment by godbout** [comment]
yes

**Comment by godbout** [comment]
> yes

hope that helps!

**Comment by godbout** [comment]
actually thinking about it more i'm not sure. personally i have **one** tab that is just a single pane, but the others are multipanes.

**Comment by amok** [comment]
I just "kill" a pane after creating if it's not needed, like

```
windows:
  - name: X
    root: X
    layout: even-vertical
    panes:
      - echo
      - exit
```
