### ISSUE TITLE
delay on window creation

### ISSUE THREAD

**Issue by le0n** [TomAnthony/itermocil#141]
Hi all, I've got the following yml file, all of the "do-xxx" are zsh aliases:

```
windows:
  - name: tunnel
    root: ~
    command: do-tunnel
  - name: sample-three-panes
    root: ~
    layout: main-horizontal
    panes:
      - do-server
      - do-webpack
      - do-job
```

the commands inside "sample-three-panes" depend on "do-tunnel" which creates a docker container. So with this yml file, when I run itermocil sample it creates two windows, but only do-tunnel runs. all of the commands in the 2nd tab runs but fails. Is there a way to introduce some delay in the 2nd window such that it runs strictly after the first window (do-tunnel)? Thanks!
