### ISSUE TITLE
Setting tab name with echo

### ISSUE THREAD

**Issue by robertmarkbram** [TomAnthony/itermocil#144]
I am trying to run a command to set a tab/pane name (not sure which is which atm) using `echo`.

```
windows:
  - name: Run-apps
    root: ~
    layout: tiled
    panes:
      - commands:
        - echo -e '\033];My tab name\007'
        - cd ~/my-app
```

When I run this I get:

```
200:201: syntax error: Expected “"” but found unknown token. (-2741)
```

Any way to make this work as I expect?

Rob
:)
