### ISSUE TITLE
Expected end of line but found class name

### ISSUE THREAD

**Issue by john-adamson** [TomAnthony/itermocil#19]
I wish to open 10 tiled terminals.  When I try to do so I receive the following error:

```
2871:2878: syntax error: Expected end of line but found class name. (-2741)
```

My yml file looks like this:

```
windows:
  - name: my_servers
    root: ~/some_important_server_directory/
    layout: tiled
    panes:
      - ssh <server 0>
      - ssh <server 1>
      - ssh <server 2>
      - ssh <server 3>
      - ssh <server 4>
      - ssh <server 5>
      - ssh <server 6>
      - ssh <server 7>
      - ssh <server 8>
      - ssh <server 9>
```
