### ISSUE TITLE
Unexpected behavior when using more than one `window`

### ISSUE THREAD

**Issue by richarddewit** [TomAnthony/itermocil#23]
Configuration:

``` yml
windows:
 - name: backend
   root: ~/dev/backend/projectname
   layout: even-horizontal
   panes:
     - commands:
       - vagrant up
       - vagrant ssh
     - charm .

 - name: frontend
   root: ~/dev/frontend/projectname
   layout: main-vertical-flipped
   panes:
     - webpack
     - npm start
     - commands:
       - charm .
       focus: true

```

What happens:
* first window gets loaded as it should
* second window only has it's first pane loaded

When I load both windows in each their own config file and calling `itermocil backend; itermocil frontend`  I get this error:
> 424:478: execution error: iTerm got an error: Can’t get session 4 of current terminal. Invalid index. (-1719)

But when I run `itermocil backend` and `itermocil frontend` separately it works as expected.
