### ISSUE TITLE
Colors per pane

### ISSUE THREAD

**Issue by nevetS** [TomAnthony/itermocil#24]
I wonder - is there a way to set the color per pane?

Also along the same lines - is there a way to specify the profile per pane?

**Comment by nevetS** [comment]
To answer my own question, it looks like iterm2 has a solution built in.  Per the [documentation page](https://www.iterm2.com/documentation-escape-codes.html), there are escape codes that can be used to solve this problem.

The escape codes are as follows:
Profile change:
```shell
^[]50;SetProfile=NewProfileName^G
```
Background Color change (where N is a number between 0 and 255)
```shell
^[]6;1;bg;red;brightness;N^G 
^[]6;1;bg;green;brightness;N^G 
^[]6;1;bg;blue;brightness;N^G
```
For me personally, the background color changes with the profile, so I added the following function to my .zshrc
```shell
chg_profile() { echo -e "\033]50;SetProfile=$1\a" }
```
And then added the command to my yaml
```yml
windows:
  - name: example
    root: ~/src
    layout: main-vertical
    panes:
      - commands:
          - chg_profile light
          - ssh me@remotehost
      - commands:
          - chg_profile dark
          - cd myprojected
      - itop

```
