### ISSUE TITLE
Is it possible to set pane title?

### ISSUE THREAD

**Issue by adisos** [TomAnthony/itermocil#28]
As you see here I set titles manually by hitting command + i and escape.
![image](https://cloud.githubusercontent.com/assets/592907/12230205/ce8aaf3e-b878-11e5-88ac-0e1f65b373e0.png)

Is it possible to set titles in yml file?

**Comment by mbollemeijer** [comment]
As far as I know, using the ```name: PaneTitle``` sets the name of a pane.

example
```yaml
windows:
  - name: Window title
    root: ~
    layout: main-horizontal
    panes:
      - commands:
        - command#1
        name: Name of pane
      - commands:
        - git status
        name: 'git'
```
