### ISSUE TITLE
Make layouts act as templates

### ISSUE THREAD

**Issue by alexfedoseev** [TomAnthony/itermocil#29]
Hi! Discussion issue about extend layouts functionality so they can accept args and params passed from the CLI (example taken from `tmuxinator`).

```bash
itermocil node-app my-project root=~/Dev/my-project
```

```
.itermocil/
  |-- node-app.yml
```

```yaml
windows:
  - name: <%= @args[0] %>         # `my-project` will be used
    root: <%= @params['root'] %>  # `~/Dev/my-project` will be used
    layout: tiled
    panes:
      - atom .
      - git status
      - npm start
```
