### ISSUE TITLE
Waiting

### ISSUE THREAD

**Issue by geddski** [TomAnthony/itermocil#3]
Is there a way to have one pane wait for another to finish before executing? My use case is around launching boot2docker and then once the VM is up running containers.

**Comment by TomAnthony** [comment]
Hey,

So there isn't anything built in (there isn't anything in teamocil, and at the moment I'm trying to maintain compatibility) - however that doesn't mean it can't be done.

I think we could create a solution using the `wait` command which is designed for this sort of scenario - however, I'm having trouble making it behave how I'd want. I'm going to keep experimenting with that and see if I can get a solution working.

In the meantime you can 'cheat' by using the `sleep` command as you can have multiple commands per pane delimited with ;. So you may try something like:

```yaml
windows:
  - name: geddski-example
    root: ~
    layout: main-vertical
    panes:
      - boot2docker init; boot2docker up
      - sleep 5; docker run first-thing
      - sleep 5; docker run second-thing
```

It isn't perfect, but it will hopefully help. If I can get a wait command solution working I'll be back. :)

**Comment by TomAnthony** [comment]
Hey again,

So I actually worked out a better solution. It is a bit more fiddly to get your head around but it does exactly what you want in an efficient manner.

It uses a named pipe. Basically it creates a pipe to communicate across the panes. Each pane then waits for a signal over that pipe (just an `echo` command which makes the `cat` commands end and the docker commands start).

I don't know boot2docker so guessed the commands you need!

```yaml
windows:
  - name: geddski
    root: ~
    layout: main-vertical
    panes:
      - mkfifo /tmp/q1; boot2docker init; boot2docker up; echo > /tmp/q1; echo > /tmp/q1
      - cat /tmp/q1; docker run first-thing
      - cat /tmp/q1; docker run second-thing
```

I've tested it with my own commands and it works perfectly. Let me know how you get on. :)

**Comment by TomAnthony** [comment]
In an attempt to tidy up this situation a bit I put together [queue](https://github.com/TomAnthony/queue). It is nice wrappers around the solution above. You can install it with `brew install TomAnthony/brews/queue` (you may need to `brew update` first).

With queue installed you can then use a solution that looks more like:

```yaml
windows:
  - name: geddski
    root: ~
    layout: main-vertical
    panes:
      - qcreate q1; boot2docker init; boot2docker up; qtrigger q1
      - qwait q1; docker run first-thing
      - qwait q1; docker run second-thing
```

Let me know if you have any problems. :)
