### ISSUE TITLE
Runs each command on all panes

### ISSUE THREAD

**Issue by zeedeveloper** [TomAnthony/itermocil#34]
Installed latest version of itermocil (0.1.8) and iTerm2 (2.1.4) with following project

```
windows:
  - name: sample
    root: ~
    layout: main-vertical-flipped
    panes:
       - echo "1"   
       - echo "2"
       - echo "3"
```

Here is output, notice all commands are executed on all panes:
<img width="1170" alt="screen shot 2016-02-04 at 11 55 09 am" src="https://cloud.githubusercontent.com/assets/3220225/12827789/3eee4388-cb36-11e5-8c24-ee0ba2d48966.png">
