### ISSUE TITLE
SSH

### ISSUE THREAD

**Issue by danielzev** [TomAnthony/itermocil#47]
Hey Tom, great app!

I'm trying to run my commands starting with an SSH into a remote box. then from there, change directories and eventually run a top or tail a log file.

so my YML file is something like this:

```
windows:
  - name: Test
    root: ~/
    layout: even-horizontal
    panes:
      - commands:
        - ssh username@host
        - sudo su - someotheruser
        - tail -f somefile
      - commands:
        - ssh username@host
        - sudo su - someotheruser
        - top
```

Though the 2nd and 3rd command execute on my shell before SSH'ing into the remote box. Now I understand why this would be tricky, though is there a way to do this?
