### ISSUE TITLE
Timing problem with tabs in iTerm 2.1.1

### ISSUE THREAD

**Issue by ze-phyr-us** [TomAnthony/itermocil#5]
Hey, this looks like a great script! I tend run commands in multiple tabs rather than panes. Do you think tab manipulation could be added to itermocil? I think it would be a good addition as you already have all that AppleScript machinery in place. 

The layout file could perhaps look like

```yaml
windows:
  - name: blah
    tabs:
      - root: ~
        layout: even-horizontal
        panes:
          - echo "pane 1"
          - echo "pane 2"
```

**Comment by TomAnthony** [comment]
Hi @ze-phyr-us,

If I understand you correctly - you can already do this. By default iTermocil opens new tmux 'windows' in new tabs (as these are more akin to tmux 'windows'). So this script would open two iTerm tabs, each running a single command:

```YAML
windows:
  - name: tab-one
    root: ~/projects/
    layout: tiled
    panes:
      - echo "this is in the first tab"
  - name: tab-two
    root: ~/projects/
    layout: tiled
    panes:
      - echo "this is in the second tab"
```

Try that and see if it does what you are looking for.

**Comment by ze-phyr-us** [comment]
Thanks, that pretty much works. In about one invocation in five, it only opens the first tab, though. I get `662:776: execution error: iTerm got an error: Can’t get session 3 of current terminal. Invalid index. (-1719)`

**Comment by TomAnthony** [comment]
@ze-phyr-us Can you tell me which version of iTerm you are using, and if possible post your YAML file. I can't replicate your issue.

I'm guessing you are on iTerm 2.1.1 - which is the latest stable build. The new beta builds have much better Applescript support. For iTerm 2.1.1 I have to do some keystroke emulation in places which I think may be explaining your problem - I think iTermocil is going too fast and trying to send commands to panes that iTerm hasn't created yet.

**Comment by ze-phyr-us** [comment]
@TomAnthony You're right, I have 2.1.1. I do want to move to the latest beta but currently don't have the time to migrate all my existing AppleScripts. I guess you can disregard this issue, it really does seem like a timing problem with keystroke emulation as you describe. 

It would still be nice to support windows _and_ tabs _and_ panes, though :-)

**Comment by TomAnthony** [comment]
@ze-phyr-us I'm leaving this open for now, as I have an idea of how to improve the timing. At the moment I wait for an arbitrary amount of time (that I got from testing) for a new tab/pane to open. However, I think I could actually use Applescript to count the panes on loop until the pane appears and then fill it in.

I'll keep you updated. If you can share your YAML (or just tell me how many windows and how many panes) then it might help me replicate the problem so I can test this. Thanks! :)

Also - regarding your suggestion for windows, tabs and panes... that is a great idea. I am working on extending so rather than just using the teamocil format I also support tmuxinator, but will also be adding my own format (which will include options for badge/tab colour etc. in iTerm) and so will definitely ensure that has windows, tabs and panes. :)

**Comment by ze-phyr-us** [comment]
So I am now able to replicate this every single time with the following YAML. `sb` is my alias for Sublime Text.

```yaml
windows:
  - name: one
    root: ~
    layout: tiled
    panes:
      - sb
  - name: two
    root: ~
    layout: tiled
    panes:
      - echo 'this one fails'
```

I thought it may have something to do with the command taking long to execute, but `sleep 10` instead of Sublime works fine. So maybe it's something about the command taking focus away from iTerm...

Great news about the new, more powerful format! Looking forward to it.
