### ISSUE TITLE
Paneless windows not working

### ISSUE THREAD

**Issue by miguelrs** [TomAnthony/itermocil#58]
I just installed iTermocil and your layout examples in `README.md` work fine, all but the last one ["A paneless window"](https://github.com/TomAnthony/itermocil#a-pane-less-window).

```
windows:
  - name: pane-less
    root: ~/Code/sample/www
    command: rails console
windows:
  - name: one_more-pane-less
    root: ~/Code/sample/www
    commands:
      - bundle update
      - rails server
```

If I put that code into a `paneless.yml` file and run `itermocil paneless`, it just opens one tab with the window defined last (`one_more-pane-less`) and runs its commands, but it completely ignores the first one (`pane-less`).

I really wanted to have one `my_big_project.yml` file where I define several windows to be opened in several tabs (some of them will be split in panels, others won't). Isn't that possible?

**Comment by miguelrs** [comment]
Ok I figured out - you have to use them like this:
```
windows:
  - name: pane-less
    root: ~/Code/sample/www
    command: rails console
  - name: one_more-pane-less
    root: ~/Code/sample/www
    commands:
      - bundle update
      - rails server
```
without defining `windows` twice, and it works ok 👌 

You may want to make the README a bit clearer though...
