### ISSUE TITLE
Using iTerm's profile

### ISSUE THREAD

**Issue by hisplan** [TomAnthony/itermocil#60]
I've already set up a bunch of profiles in iTerm2 (pane name, badge, ssh command, colors, font, and etc.), and would like to reuse this profile by specifying in itermocil's yaml file. Is this possible?

**Comment by jlhall** [comment]
@hisplan 
If you mean you would like to be able to create a layout and have each pane/etc follow a different profile, I'm unclear if that is supported on itermocil's end.

However, I was able to find a proprietary iTerm command you can run to dynamically change profiles on the fly, and I believe (haven't tested) that this will work in the yaml.

``` ^[]1337;SetProfile=NewProfileName^G ```
[Taken from here](https://iterm2.com/documentation-one-page.html)

So your yaml might look like this:
```
windows:
  - name: _tiled_4_panes
    root: ~
    layout: tiled
    panes:
      - ^[]1337;SetProfile=NewProfileName^G
      - ^[]1337;SetProfile=NewProfileName^G
      - ^[]1337;SetProfile=NewProfileName^G
      - ^[]1337;SetProfile=NewProfileName^G
```
Just replace the NewProfileName with what you need.

A Safer Solution...
...is to setup iTerm with Automatic Profile Switching via Shell Integration (same resource linked above, just search), and thereby avoid any unintended consequences when using tmux or other services. In this way, your terminal panes will adjust their profile based on available information, like the current directory etc. For instance this...
```
windows:
  - name: _tiled_4_panes
    root: ~
    layout: tiled
    panes:
      - cd js/
      - cd py/
      - cd tests/
      - [your editor command] ./README.md
```
...with automatic profile switching, would have your Javascript profile, Python profile, Testing profile, and Editing profile active in each of the respective panes, as iTerm would recognize the directory/file pattern without you needing to programmatically swap to the profile with a [CAUTIONED] escape code.

Cheers. If this solves your issue, please remember to close the issue!
