### ISSUE TITLE
Pane-less window malfunctions

### ISSUE THREAD

**Issue by AdrianTP** [TomAnthony/itermocil#61]
The following iTermocil config:
```yml
windows:
  - name: test
    root: ~
    command: echo 'hello'
```
 results in the following output:
```
Last login: Tue May  2 13:35:58 on ttys019
e; c; h; o;  ; '; h; e; l; l; o; '
<compname>:~ <username>$ e; c; h; o;  ; '; h; e; l; l; o; '
-bash: syntax error near unexpected token `;'
<compname>:~ <username>$
```

It seems I am unable to open a pane-less window.

```
$ itermocil --version
0.2.1
```
...installed via homebrew
