### ISSUE TITLE
itermocil opening layout in a new tab

### ISSUE THREAD

**Issue by lucasfeliciano** [TomAnthony/itermocil#62]
I don't know if the expected behaviour but i think this is really "annoying"

I'm using this layout:

```yml
windows:
  - name: sample-3-columns
    root: ~/Projects/Website
    layout: 3_columns
    panes:
      - echo "bla"
      - echo "bla"
      - echo "bla"
      - echo "bla"
```

Is it because a iTerm option or something like this?
