### ISSUE TITLE
Use the cwd as root for relative paths

### ISSUE THREAD

**Issue by jeffijoe** [TomAnthony/itermocil#63]
It would be awesome if you were to use `itermocil` in a directory, that all `root`s specified as relative paths (or if omitted) would be relative to the current working directory.

```
windows:
  - root: some-api
  ...
  - root: other-api
```

```
~/Projects/my-company> $ itermocil
```
