### ISSUE TITLE
command strings executed in shell as array of characters

### ISSUE THREAD

**Issue by kevzettler** [TomAnthony/itermocil#82]
I have the following `iTermocil.yml` file in my projects directory

``` yaml
windows:
  - name: client-dev
    root: ./
    command: yarn client-dev
  - name: server-dev
    root: ./
    command: yarn server-dev
```

When I execute `itermocil`  iTerm opens 2 new tabs and executes the commands as semicolon delimited arrays of characters like:

```bash
Kevs-MBP-2:cra kev$ y; a; r; n;  ; c; l; i; e; n; t; -; d; e; v
-bash: syntax error near unexpected token `;'
```

and

```
Kevs-MBP-2:cra kev$ y; a; r; n;  ; s; e; r; v; e; r; -; d; e; v
-bash: syntax error near unexpected token `;'
```

This fails to actually execute the commands

**Comment by kevzettler** [comment]
This is

iTerm2: `Build 3.1.6beta5` and

```
itermocil --version
0.2.1
```

**Comment by TomAnthony** [comment]
@kevzettler Slow reply, sorry.

That is really weird. Did it work after an iTerm update?

**Comment by kevzettler** [comment]
I had to update the yaml to prefix the commands with a hyphen like:
```
windows:
  - name: client
    commands:
      - yarn dev-client
  - name: server
    layout: even-vertical
    panes:
      - yarn dev-server
      - nodemon build/server.js
```
