### ISSUE TITLE
itermocil doesn't found the file

### ISSUE THREAD

**Issue by xavierartot** [TomAnthony/itermocil#86]
![screen shot 2018-08-29 at 9 22 39 pm](https://user-images.githubusercontent.com/5130192/44825810-db444880-abd1-11e8-99c2-48fe3cd6ff90.png)

here my file would-you-rather
```
windows:
  - name: would-you-rather
    root: /Applications/MAMP/htdocs/nanodegree/redux/would-you-rather
    layout: even-horizontal
    panes:
      - commands:
        - cd src/
        - vim index.js
        focus: true
      - commands:
        - cd src/ && yarn start
```
