### ISSUE TITLE
iTermocil not working on iTerm2 3.3

### ISSUE THREAD

**Issue by AlecRust** [TomAnthony/itermocil#97]
After upgrading my iTerm2 today to 3.3.0beta1 my iTermocil scripts are no longer working.

When I run `itermocil my_project` the correct panels are created, but only the command(s) for the first panel run:

![screenshot](https://user-images.githubusercontent.com/247634/54882508-aee46800-4e52-11e9-81dc-929616684440.png)

**Comment by AlecRust** [comment]
I've taken this opportunity to switch to tmux/tmuxinator, using [iTerm2 tmux integration](https://www.iterm2.com/documentation-tmux-integration.html) to achieve the same native iTerm2 panels and tabs as iTermocil but with the session saving and other benefits of tmux.

Here's my old iTermocil project vs the new Tmuxinator project:

**~/.itermocil/project_name.yml**
```yaml
windows:
  - name: project_name
    root: ~/projects/project_name
    layout: even-horizontal
    panes:
      - bin/rails server
      - commands:
        - stree .; code .; chrome "http://localhost:3000/" --new-window; git status
        focus: true
```

**~/.config/tmuxinator/project_name.yml**
```yaml
name: project_name
root: ~/projects/project_name

# Specifies (by index) which pane of the specified window will be selected on startup
startup_pane: 4

# Disable default attaching to use custom on_project_exit attach
attach: false

# Attach to tmux with custom options (iTerm2 tmux integration)
on_project_exit: tmux -CC attach -t project_name

windows:
  - project_name:
      layout: even-horizontal
      panes:
        - bin/rails server
        - stree .; code .; chrome "http://localhost:3000/" --new-window; git status
```

**Comment by GrantCodesCodes** [comment]
I tried downgrading iTerm to older 2.x versions, and it was still broken. On my old computer using the same itermocil version it was working fine. The only difference in system/iTerm settings was Full Disc Access for iTerm2 in system accessibility settings. After removing this and restarting iTerm things worked. Not 100% sure if it's related but might help for you...

**Comment by kevzettler** [comment]
I just upgraded iterm and my whole workflow is broken

seeing:
```
$ itermocil
no root!
no root!
no root!
no root!
567:571: execution error: iTerm got an error: AppleEvent handler failed. (-10000)
```

my Itermocil.yml is:

```
windows:
  - name: client
    commands:
      - yarn dev-client
  - name: server
    layout: even-vertical
    panes:
      - yarn dev-server
      - nodemon --inspect build/server.js
  - name: signalhub
    commands:
      - docker-compose -f ./devops/docker-compose.yml up -d signalhub && docker logs -f devops_signalhub_1
  - name: turnserver
    commands:
      - docker-compose -f ./devops/docker-compose.yml up -d turnserver && docker logs -f devops_turnserver_1
```

Only seeing 3 iterm tabs launched as opposed to 4
